server:
  port: 8089

spring:
  application:
    name: @app.name@
  datasource:
    url: @spring.datasource.url@
    username: @spring.datasource.username@
    password: @spring.datasource.password@
    driverClassName: @spring.datasource.driverClassName@

hikaricp:
  connectionTimeout: @hikaricp.connectionTimeout@
  idleTimeout: @hikaricp.idleTimeout@
  maxLifetime: @hikaricp.maxLifetime@
  maximumPoolSize: @hikaricp.maximumPoolSize@
  minimumIdle: @hikaricp.minimumIdle@
  poolName: @hikaricp.poolName@


logging:
  config: classpath:log4j2.xml

redis:
  address: @redis.address@
  idleConnectionTimeout: @redis.idleConnectionTimeout@
  connectTimeout: @redis.connectTimeout@
  timeout: @redis.timeout@
  retryAttempts: @redis.retryAttempts@
  retryInterval: @redis.retryInterval@
  connectionMinimumIdleSize: @redis.connectionMinimumIdleSize@
  connectionPoolSize: @redis.connectionPoolSize@



redis-client:
  service: @redis-client.service@
  timeout: @redis-client.timeout@
  pool:
    maxIdle: @redis-client.pool.maxIdle@
    maxTotal: @redis-client.pool.maxTotal@
    maxWaitMillis: @redis-client.pool.maxWaitMillis@
    testOnBorrow: @redis-client.pool.testOnBorrow@


arthas:
  agent-id: @app.name@
  tunnel-server: ws://127.0.0.1:7777/ws
